name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test (Elixir ${{ matrix.elixir }} | Erlang/OTP ${{ matrix.otp }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - otp: "27.2"
            elixir: "1.18"
            coverage: true
            lint: true

          - otp: "25.0"
            elixir: "1.18"
            os: "ubuntu-22.04"

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MIX_ENV: test

    steps:
      - name: Clone this repository
        uses: actions/checkout@v4

      - name: Install Erlang/OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
          version-type: strict

      - name: Cache built dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key:
            ${{ runner.os }}-mix-otp${{ matrix.otp }}-elixir${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-otp${{ matrix.otp }}-elixir${{ matrix.elixir }}-

      - name: Install and compile dependencies
        run: mix do deps.get, deps.compile

      - name: Check formatting
        run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - name: Check no unused dependencies
        run: mix do deps.get --only test, deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - name: Compile with --warnings-as-errors
        run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - name: Run tests with coverage
        run: mix coveralls.github
        if: ${{ matrix.coverage }}

      - name: Run tests
        run: mix test
        if: ${{ !matrix.coverage }}
